### ISSUE TITLE
Dropout in the top-k guided memory matching module and the value of query(r2,r3)

### ISSUE THREAD

**Issue by LingyiHongfd** [Hongje/HMMN#1]
Excellent work!
I have some question about the dropout in the top-k guided memory matching module and the value of query(r2,r3).
In your code, you doesn't use the value of query of r2 and r3 stage, but in the paper you use the value to generate Z3.  The operation in the code is different from the description in the paper.

**Comment by Hongje** [comment]
Thank you for your interest.
1) The value of query(r2,r3) is used in Decoder.
https://github.com/Hongje/HMMN/blob/76a6b63b72ae7fa95011d2b58ee0fa45b5b36389/model.py#L418
In the above code, `r3e` and `r2e` are extracted from the query encoder.
https://github.com/Hongje/HMMN/blob/76a6b63b72ae7fa95011d2b58ee0fa45b5b36389/model.py#L121
Then, `r3e` and `r2e` will be fed to `self.convFS()` in Decoder, and it is the value of query in the paper.
The reason why I extracted value in Decoder is that I want to keep the original architecture of the base code, STM [[link](https://github.com/seoungwugoh/STM)].
2) Can you explain the question about the dropout in more detail?
If your question was about the implementation of the dropout during training, then below will be a good reference.
Just change the code in model.py ([#L121](https://github.com/Hongje/HMMN/blob/76a6b63b72ae7fa95011d2b58ee0fa45b5b36389/model.py#L121)) to
```python
if random.random() < 0.5:
        s = self.convFS(f) + self.convMemory(mem)
else:
        s = self.convFS(f)
```

**Comment by LingyiHongfd** [comment]
Your comment is a good answer to my question. Many thanks
