### ISSUE TITLE
question about the top-k guided memory matching

### ISSUE THREAD

**Issue by DavidKong96** [Hongje/HMMN#3]
thanks for your sharing . wonderful job,
but why i didn't see the dropout in top-k guided memory matching and the conv3*3 before it in your code.
and the KV_Q_r3 = KeyValue(512, keydim=128, valdim=-1, only_key=True) means there is no need for values.
What do I understand it ?

**Comment by Hongje** [comment]
Hi,
I think your questions are almost overlapped with https://github.com/Hongje/HMMN/issues/1#issue-1023490650
Please refer to the reply on that.
If you have any further questions, feel free to leave a comment.

**Comment by DavidKong96** [comment]
> Hi, I think your questions are almost overlapped with [#1 (comment)](https://github.com/Hongje/HMMN/issues/1#issue-1023490650) Please refer to the reply on that.

thanks for your reply, get it.
