### ISSUE TITLE
Regarding the results on YouTube-VOS

### ISSUE THREAD

**Issue by z-x-yang** [Hongje/HMMN#5]
Hi, 

THX for releasing the inference code of DAVIS.

May I ask what frame rate did you use in the evaluation of HMMN and KMN on YouTube-VOS? Validation or Validation All Frames? 6FPS or 30FPS?

Best.

**Comment by Hongje** [comment]
Hi,

Thanks for your interest.

I used Validation All Frames in the evaluation of HMMN and KMN on YouTube-VOS.

**Comment by z-x-yang** [comment]
Got it! THX!
